//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NubeBooks.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProforma
    {
        public int IdProforma { get; set; }
        public int IdItem { get; set; }
        public int Cantidad { get; set; }
        public Nullable<decimal> PrecioUnudad { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public Nullable<decimal> PorcentajeIgv { get; set; }
        public Nullable<decimal> IgV { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Proforma Proforma { get; set; }
    }
}
