//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NubeBooks.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProforma
    {
        public int IdDetalleProforma { get; set; }
        public int IdProforma { get; set; }
        public int IdItem { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnidad { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public Nullable<decimal> PorcentajeIgv { get; set; }
        public Nullable<decimal> Igv { get; set; }
        public string UnidadMedida { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Proforma Proforma { get; set; }
    }
}
