//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NubeBooks.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaMovimientoInv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormaMovimientoInv()
        {
            this.MovimientoInv = new HashSet<MovimientoInv>();
        }
    
        public int IdFormaMovimientoInv { get; set; }
        public int IdTipoMovimientoInv { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
    
        public virtual TipoMovimientoInv TipoMovimientoInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoInv> MovimientoInv { get; set; }
    }
}
