//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NubeBooks.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int IdMovimiento { get; set; }
        public int IdCuentaBancaria { get; set; }
        public Nullable<int> IdEntidadResponsable { get; set; }
        public int IdFormaMovimiento { get; set; }
        public int IdEstadoMovimiento { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdComprobante { get; set; }
        public string NroOperacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public Nullable<decimal> MontoSinIGV { get; set; }
        public decimal TipoCambio { get; set; }
        public string NumeroDocumento { get; set; }
        public string Comentario { get; set; }
        public bool Estado { get; set; }
        public int UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<decimal> SaldoBancario { get; set; }
        public Nullable<int> IdLogUsuario { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Comprobante Comprobante { get; set; }
        public virtual CuentaBancaria CuentaBancaria { get; set; }
        public virtual EntidadResponsable EntidadResponsable { get; set; }
        public virtual EstadoMovimiento EstadoMovimiento { get; set; }
        public virtual FormaMovimiento FormaMovimiento { get; set; }
        public virtual LogUsuario LogUsuario { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
